### ISSUE TITLE
Uploading to PyPi with Zip file

### ISSUE THREAD

**Issue by DenisCarriere** [themiurgo/ratelim#7]
Someone mentioned to me that your PyPi package doesn't contain a Zip file in your latest release.

He was running a linux OS and couldn't install it from the setup.py file.

When uploading wheel also include `sdist` for the zip fie.

```bash
$ python setup.py sdist bdist_wheel upload
```

**Comment by themiurgo** [comment]
Thanks a lot for catching this, I didn't realise it. Now it's fixed. Cheers!

**Comment by DenisCarriere** [comment]
Thanks! Yea I presented my geocoder at a local Meetup and someone spotted that. Thanks for quick fix!
